name: 🚸 pre-commit

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pre-commit:
    runs-on: Ubuntu-Latest

    steps:
      - name: 🚸 Run pre-commit
        uses: 5ouma/utils/pre-commit@1aafaa1aac6f2b28c28be9cf561b92278814c396 # main
